"""create initial schema

Revision ID: b581045cf266
Revises:
Create Date: 2026-01-26 22:33:55.444161

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b581045cf266"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equity_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("equity_usd", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("cash_usd", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("unrealized_pnl_usd", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("realized_pnl_today_usd", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("open_positions", sa.Integer(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_equity_snapshots_ts",
        "equity_snapshots",
        [sa.literal_column("ts DESC")],
        unique=False,
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("entry_price", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("entry_qty", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("entry_notional_usd", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("stop_price", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("take_profit_price", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column(
            "trailing_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("trailing_offset", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("exit_price", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("realized_pnl_usd", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("fees_paid_usd", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("slippage_est_usd", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("notes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_trades_status", "trades", ["status"], unique=False)
    op.create_index(
        "ix_trades_symbol_opened_at",
        "trades",
        ["symbol", sa.literal_column("opened_at DESC")],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_table(
        "bot_config_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("config_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("config_hash", sa.Text(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version", name="uq_bot_config_versions_version"),
    )
    op.create_index(
        "uq_bot_config_versions_is_active",
        "bot_config_versions",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("level", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=True),
        sa.Column("trade_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("public_safe", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["trade_id"], ["trades.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_events_public_safe", "events", ["public_safe"], unique=False)
    op.create_index("ix_events_symbol", "events", ["symbol"], unique=False)
    op.create_index("ix_events_ts", "events", [sa.literal_column("ts DESC")], unique=False)
    op.create_index("ix_events_type", "events", ["type"], unique=False)
    op.create_table(
        "exchange_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("exchange", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("key_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trade_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("order_type", sa.Text(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("price", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("exchange_order_id", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["trade_id"], ["trades.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_orders_exchange_order_id", "orders", ["exchange_order_id"], unique=False)
    op.create_index(
        "ix_orders_symbol_created_at",
        "orders",
        ["symbol", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("ix_orders_trade_id", "orders", ["trade_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_orders_trade_id", table_name="orders")
    op.drop_index("ix_orders_symbol_created_at", table_name="orders")
    op.drop_index("ix_orders_exchange_order_id", table_name="orders")
    op.drop_table("orders")
    op.drop_table("exchange_keys")
    op.drop_index("ix_events_type", table_name="events")
    op.drop_index("ix_events_ts", table_name="events")
    op.drop_index("ix_events_symbol", table_name="events")
    op.drop_index("ix_events_public_safe", table_name="events")
    op.drop_table("events")
    op.drop_index(
        "uq_bot_config_versions_is_active",
        table_name="bot_config_versions",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("bot_config_versions")
    op.drop_table("users")
    op.drop_index("ix_trades_symbol_opened_at", table_name="trades")
    op.drop_index("ix_trades_status", table_name="trades")
    op.drop_table("trades")
    op.drop_index("ix_equity_snapshots_ts", table_name="equity_snapshots")
    op.drop_table("equity_snapshots")
    # ### end Alembic commands ###
